# Generated by Django 5.1.2 on 2024-10-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('payment', 'Payment'), ('deposit', 'Deposit')], max_length=10),
        ),
        migrations.DeleteModel(
            name='WithdrawRequest',
        ),
    ]
